apiVersion: v1
kind: Secret
metadata:
  name: cloudnotes-secret
  namespace: cloudnotes
data:
  DB_PASSWORD: UHJlbUthcmFkMTg3Mw==
  DB_USER: cHJlbQ==
  SESSION_SECRET: Mmc1ZjJzZGEyaElBTWlValZYRWhMeVFDdGMraHRwdVFyK3MzcWlXT2JBUT0=